version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - data_volume:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    container_name: my_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
      
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongoDB_Data:/var/lib/mongodb/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    networks:
      - my_network
    depends_on:
      - postgres
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

volumes:
  data_volume:
    external: true
  mongoDB_Data:
    external: true

networks:
  my_network:
    driver: bridge
